### ISSUE TITLE
Menu System: Splash Screen

### ISSUE THREAD

**Issue by Kuoni** [Kuoni/VegaNova#13]
The splash screen can also duplicate as a boot loader in which you can do initialization for your game.
# Tasks
- [x] Add a generic placeholder for the splash
- [x] In the Update function use a parametrize parameter to know when the splash is done
- [x] Once the splash is done forward the user to the main menu.

**Comment by Kuoni** [comment]
CL#00021. The generic placeholder is the same Skybox that is present in the Main Menu. Once the timer expires, the player is forwarded to the Main Menu Scene.
