### ISSUE TITLE
Saving a Game Tutorial

### ISSUE THREAD

**Issue by Kuoni** [Kuoni/VegaNova#15]
Part 18, save your game using the pause menu.
# Tasks
- [ ] Confirm Dialog
- [ ] Overwrite Save
- [ ] Save Environment Objects (Light, Terrain, etc)
- [ ] Save World Objects (Units and Buildings)
- [ ] Name and Time for save games
- [ ] Finish Prefab and reuse for loading.
