### ISSUE TITLE
Loading a game Tutorial

### ISSUE THREAD

**Issue by Kuoni** [Kuoni/VegaNova#16]
Loading a game from the menu. Part 19.
# Tasks
- [ ] Pause Menu Load
- [ ] Main Menu Load + Full Load Menu Scene (no prefab but copy paste Canvas?)
- [ ] Load Menu screen and script.
- [ ] Confirm in Pause Menu.
- [ ] Cancel / Return to Previous
- [ ] Actual World Loading.
- [ ] Load of JSON.
- [ ] Reuse prefab for Save Game.
